### PR TITLE
rune/attest.go && libenclave: drop the linkable input  parameter and sync up to the newest quote types in the intelsgx package

### PR DESCRIPTION
**Pull request by hustliyilin**
Signed-off-by: Yilin Li <YiLin.Li@linux.alibaba.com>

### CODE REVIEW

**Comment by jiazhang0** [comment]
CI/CD reports failure. Please fix them.

**Comment by hustliyilin** [comment]
> CI/CD reports failure. Please fix them. @hustliyilin

This pr revises the cli parameters of the `rune attest` command,  So the skeleton CI/CD will fail. And I add the new CI/CD in the second commit of this pr, I also review the readme in the third commit of this pr.

**Comment by jiazhang0** [comment]
> > CI/CD reports failure. Please fix them. @hustliyilin
> 
> This pr revises the cli parameters of the `rune attest` command, So the skeleton CI/CD will fail. And I add the new CI/CD in the second commit of this pr, I also review the readme in the third commit of this pr.

OK

**Comment by hustliyilin** [comment]
This Conflicting files I will fix it in the tomorrow night.

**Comment by hustliyilin** [comment]
> This Conflicting files I will fix it in the tomorrow night.

the conflict is fixed@jiazhang0 .

**Pull request merged**
