### PR TITLE
[HUST CSE]optimize: rune/vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c

### PR DESCRIPTION
**Pull request by AuroraHaaash**
Hi, I've recently got involved in some work related to inclavare, so I spent some time reading the source code. 
And I found something pointless in the underlined file.
I optimized code, and happened to found that the source code of this file in opencontainers is the same to my modified version.
Hope For Your Reply, THX

### CODE REVIEW

**Review by jiazhang0 — APPROVED** [review]

**Comment by hustliyilin** [comment]
Thanks for your patch @AuroraHaaash ,

This patch is same as the [patch](https://github.com/opencontainers/runc/commit/2ab6484ff627aa6177b6471c486c5d1a24b7d8db) in the runc repo.

However，you need to update the `github.com/opencontainers/runc v1.0.3` version in the [rune/go.mod](https://github.com/inclavare-containers/inclavare-containers/blob/master/rune/go.mod#L18)  rather than mofidying the codes in vendor.

**Comment by AuroraHaaash** [comment]
> Thanks for your patch @AuroraHaaash ,
> 
> This patch is same as the [patch](https://github.com/opencontainers/runc/commit/2ab6484ff627aa6177b6471c486c5d1a24b7d8db) in the runc repo.
> 
> However，you need to update the `github.com/opencontainers/runc v1.0.3` version in the [rune/go.mod](https://github.com/inclavare-containers/inclavare-containers/blob/master/rune/go.mod#L18) rather than mofidying the codes in vendor.

OK, since I'm not very familiar with go, I firstly modified the codes on myself. Anyway THX for reply.

**Comment by hustliyilin** [comment]
> > Thanks for your patch @AuroraHaaash ,
> > This patch is same as the [patch](https://github.com/opencontainers/runc/commit/2ab6484ff627aa6177b6471c486c5d1a24b7d8db) in the runc repo.
> > However，you need to update the `github.com/opencontainers/runc v1.0.3` version in the [rune/go.mod](https://github.com/inclavare-containers/inclavare-containers/blob/master/rune/go.mod#L18) rather than mofidying the codes in vendor.
> 
> OK, since I'm not very familiar with go, I firstly modified the codes on myself. Anyway THX for reply.

The codes under the vendor directory are the codes of other repos. Generally, Golang developers will not directly modify the code under the vendor. If we modify the vendor, we have to maintain these codes by ourselves, which is not very friendly to our future work.

But your codes are right, `runc` merged the similar codes. If you want to merge this part of codes, you can update a later version of runc which includes this patch as I said. If you have any questions about inclavare containers or  golang, please feel free to communicate with me.

By the way, `[HUST CSE]` means Huazhong University of Science and Technology Computer Science and Engineering？ Maybe we are alumni. It's better to add these information at the end of commit log, such as `Signed-off-by: xxx <xxx@linux.alibaba.com>`.

**Comment by AuroraHaaash** [comment]
> > > Thanks for your patch @AuroraHaaash ,
> > > This patch is same as the [patch](https://github.com/opencontainers/runc/commit/2ab6484ff627aa6177b6471c486c5d1a24b7d8db) in the runc repo.
> > > However，you need to update the `github.com/opencontainers/runc v1.0.3` version in the [rune/go.mod](https://github.com/inclavare-containers/inclavare-containers/blob/master/rune/go.mod#L18) rather than mofidying the codes in vendor.
> > 
> > 
> > OK, since I'm not very familiar with go, I firstly modified the codes on myself. Anyway THX for reply.
> 
> The codes under the vendor directory are the codes of other repos. Generally, Golang developers will not directly modify the code under the vendor. If we modify the vendor, we have to maintain these codes by ourselves, which is not very friendly to our future work.
> 
> But your codes are right, `runc` merged the similar codes. If you want to merge this part of codes, you can update a later version of runc which includes this patch as I said. If you have any questions about inclavare containers or golang, please feel free to communicate with me.
> 
> By the way, `[HUST CSE]` means Huazhong University of Science and Technology Computer Science and Engineering？ Maybe we are alumni. It's better to add these information at the end of commit log, such as `Signed-off-by: xxx <xxx@linux.alibaba.com>`.

YES, [HUST CSE] exactly means Huazhong University of Science and Technology Computer Science and Engineering

I have some preparation works about TEE for my future works toward my master degree. Although I'll mainly work on ARM TEEs, I'm assigned to read the codes of some open source projects, maybe like sgx.

AND, "add these information at the end of commit log, such as Signed-off-by: xxx <xxx@linux.alibaba.com>" , really THX for your advise.

**Comment by hustliyilin** [comment]
> > > > Thanks for your patch @AuroraHaaash ,
> > > > This patch is same as the [patch](https://github.com/opencontainers/runc/commit/2ab6484ff627aa6177b6471c486c5d1a24b7d8db) in the runc repo.
> > > > However，you need to update the `github.com/opencontainers/runc v1.0.3` version in the [rune/go.mod](https://github.com/inclavare-containers/inclavare-containers/blob/master/rune/go.mod#L18) rather than mofidying the codes in vendor.
> > > 
> > > 
> > > OK, since I'm not very familiar with go, I firstly modified the codes on myself. Anyway THX for reply.
> > 
> > 
> > The codes under the vendor directory are the codes of other repos. Generally, Golang developers will not directly modify the code under the vendor. If we modify the vendor, we have to maintain these codes by ourselves, which is not very friendly to our future work.
> > But your codes are right, `runc` merged the similar codes. If you want to merge this part of codes, you can update a later version of runc which includes this patch as I said. If you have any questions about inclavare containers or golang, please feel free to communicate with me.
> > By the way, `[HUST CSE]` means Huazhong University of Science and Technology Computer Science and Engineering？ Maybe we are alumni. It's better to add these information at the end of commit log, such as `Signed-off-by: xxx <xxx@linux.alibaba.com>`.
> 
> YES, [HUST CSE] exactly means Huazhong University of Science and Technology Computer Science and Engineering
> 
> I have some preparation works about TEE for my future works toward my master degree. Although I'll mainly work on ARM TEEs, I'm assigned to read the codes of some open source projects, maybe like sgx.
> 
> AND, "add these information at the end of commit log, such as Signed-off-by: xxx [xxx@linux.alibaba.com](mailto:xxx@linux.alibaba.com)" , really THX for your advise.

Maybe you can add the CNCC Sig by Ding Talk to learn more information about TEEs.

image

**Comment by AuroraHaaash** [comment]
> > > > > Thanks for your patch @AuroraHaaash ,
> > > > > This patch is same as the [patch](https://github.com/opencontainers/runc/commit/2ab6484ff627aa6177b6471c486c5d1a24b7d8db) in the runc repo.
> > > > > However，you need to update the `github.com/opencontainers/runc v1.0.3` version in the [rune/go.mod](https://github.com/inclavare-containers/inclavare-containers/blob/master/rune/go.mod#L18) rather than mofidying the codes in vendor.
> > > > 
> > > > 
> > > > OK, since I'm not very familiar with go, I firstly modified the codes on myself. Anyway THX for reply.
> > > 
> > > 
> > > The codes under the vendor directory are the codes of other repos. Generally, Golang developers will not directly modify the code under the vendor. If we modify the vendor, we have to maintain these codes by ourselves, which is not very friendly to our future work.
> > > But your codes are right, `runc` merged the similar codes. If you want to merge this part of codes, you can update a later version of runc which includes this patch as I said. If you have any questions about inclavare containers or golang, please feel free to communicate with me.
> > > By the way, `[HUST CSE]` means Huazhong University of Science and Technology Computer Science and Engineering？ Maybe we are alumni. It's better to add these information at the end of commit log, such as `Signed-off-by: xxx <xxx@linux.alibaba.com>`.
> > 
> > 
> > YES, [HUST CSE] exactly means Huazhong University of Science and Technology Computer Science and Engineering
> > I have some preparation works about TEE for my future works toward my master degree. Although I'll mainly work on ARM TEEs, I'm assigned to read the codes of some open source projects, maybe like sgx.
> > AND, "add these information at the end of commit log, such as Signed-off-by: xxx [xxx@linux.alibaba.com](mailto:xxx@linux.alibaba.com)" , really THX for your advise.
> 
> Maybe you can add the CNCC Sig by Ding Talk to learn more information about TEEs.
> 
> image

GOT IT!
REALLY REALLY THX a lot.
By the way, I wonder how the Basic Compilation Check took so much time, Is there something I need to do for the action work?

**Comment by hustliyilin** [comment]
I guess the machine is stopped so you can ingore it.

**Comment by AuroraHaaash** [comment]
> I guess the machine is stopped so you can ingore it.

ok...

**Pull request merged**
