### PR TITLE
CI/CD: build and install shelter rpm failed

### PR DESCRIPTION
**Pull request by zhiminghufighting**
Fixes: #828
Signed-off-by: zhiminghufighting <zhiming.hu@intel.com>

### CODE REVIEW

**Comment by hustliyilin** [comment]
Could you provide the test results（rpm build results） in the centos and ubuntu? Thanks @zhiminghufighting

**Comment by zhiminghufighting** [comment]
> Could you provide the test results（rpm build results） in the centos and ubuntu? Thanks @zhiminghufighting

[root@BMC000000000000 inclavare-containers-0.6.0]# rpm -ivh shelter-0.6.0-1.el8.x86_64.rpm
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:shelter-0.6.0-1.el8              ################################# [100%]

**Comment by hustliyilin** [comment]
LGTM. so where is the shelter ubuntu deb package test result?

**Comment by zhiminghufighting** [comment]
shelter running log after installed by rpm as below:

[root@BMC000000000000 inclavare-containers-0.6.0]# shelter
NAME:
   shelter - shelter as a remote attestation tool for workload runing in enclave containers.

USAGE:
   shelter [global options] command [command options] [arguments...]

VERSION:
   0.0.1

COMMANDS:
   remoteattestation  attest IAS report obtained by inclavared and setup TLS security channel with inclavared
   mrverify           download target source code to rebuild and caculate launch measurement based on software algorithm and then compare with launch measurement in sigsturct file
   help, h            Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --verbose      enable verbose output
   --help, -h     show help
   --version, -v  print the version

**Comment by hustliyilin** [comment]
> 
> 
> > Could you provide the test results（rpm build results） in the centos and ubuntu? Thanks @zhiminghufighting
> 
> [root@BMC000000000000 inclavare-containers-0.6.0]# rpm -ivh shelter-0.6.0-1.el8.x86_64.rpm
> Verifying... ################################# [100%]
> Preparing... ################################# [100%]
> Updating / installing...
> 1:shelter-0.6.0-1.el8 ################################# [100%]
> 
> This is the test result in RHEL 4.18 in my local SGX2 test machine.

LGTM. so where is the shelter ubuntu deb package test result?

**Comment by zhiminghufighting** [comment]
> LGTM. so where is the shelter ubuntu deb package test result?

This patch is only for the rpm issue. 

And there is some issue in building deb package. And i am not sure if the issue is related with my environment or shelter code. If it is code issue, I will open other issue for deb package.

**Comment by hustliyilin** [comment]
> 
> 
> > LGTM. so where is the shelter ubuntu deb package test result?
> 
> This patch is only for the rpm issue.
> 
> And there is some issue in building deb package. And i am not sure if the issue is related with my environment or shelter code. If it is code issue, I will open other issue for deb package.

Ok, you need open a new issue about the shelter ubuntu deb package. Then I'll merge it.

**Comment by hustliyilin** [comment]
I add  #894 to trace the ubuntu deb package problem.

**Pull request merged**
